stages:
  - test
  - build

test:
  - stage: "Tests"
    name: "Unit Tests"
    language: php
    php:
      - 7.4
    script:
      - composer install
      - composer test
      - php travis/coverage-checker.php build/logs/clover.xml 80

build:
  - stage: "Build"
    name: "Build and deploy"
    language: generic
    before_install:
      - docker-compose up --build -d php
