language: php

services:
  - docker

before_install:
  docker build -t php-skeleton .

script:
  - docker exec -it php-skeleton bash composer test && php travis/coverage-checker.php build/logs/clover.xml 80
