language: php
#php:
#  - 7.4
services:
  - docker

before_install:
  docker build -t oitimon/php-skeleton .

script:
  - composer install
  - composer test
  - php travis/coverage-checker.php build/logs/clover.xml 80
