language: generic

before_install:
  - docker-compose up --build -d
  - docker ps -a

script:
  - docker exec -it php-skeleton bash composer test && php travis/coverage-checker.php build/logs/clover.xml 80
